### PR TITLE
Fix use after free with script timing in LuaMan.cpp

### LINKED ISSUE #219: Crash when detaching weapon from Combat Shield
**Describe the bug**
Game crashes with
`app/bin/CortexCommand: line 44:    15 Aborted                 (core dumped) "/app/lib/CortexCommand/CortexCommand" $@`
when trying to detach weapon from Combat Shield

**To Reproduce**
1. Spawn someone with Combat Shield and attachable weapon
2. Attach the weapon to the shield
3. Select "Detach" from the circular menu

It doesn't happen 100% of the time but I was able to detach at most once before crashing.

**Additional context**
Tested on 6.2.2 installed via flatpak.

```
           PID: 19050 (CortexCommand)
           UID: 1000 (user)
           GID: 1000 (user)
        Signal: 6 (ABRT)
     Timestamp: Mon 2025-09-01 18:26:27 CEST (1min 52s ago)
  Command Line: /app/lib/CortexCommand/CortexCommand
    Executable: /app/lib/CortexCommand/CortexCommand
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-flatpak-io.github.cortex_command_community.Cortex\x2dCommand\x2dCommunity\x2dProject-19026.scope
          Unit: user@1000.service
     User Unit: app-flatpak-io.github.cortex_command_community.Cortex\x2dCommand\x2dCommunity\x2dProject-19026.scope
         Slice: user-1000.slice
     Owner UID: 1000 (user)
       Boot ID: e688771a35de441ab297081937eef877
    Machine ID: 14fbba364bc84d1f8230c3bb008bb057
      Hostname: hostname
       Storage: /var/lib/systemd/coredump/core.CortexCommand.1000.e688771a35de441ab297081937eef877.19050.1756743987000000.zst (present)
  Size on Disk: 274.1M
       Message: Process 19050 (CortexCommand) of user 1000 dumped core.
```
                
                Stack trace of thread 15:
                #0  0x000078b1cf09b344 n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x9a344)
                #1  0x000078b1cf04250e n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x4150e)
                #2  0x000078b1cf029882 n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x28882)
                #3  0x000064d28644f4bc n/a (/app/lib/CortexCommand/CortexCommand + 0xd84bc)
                #4  0x000078b1cf0425c0 n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x415c0)
                #5  0x000064d28699c23c n/a (/app/lib/CortexCommand/CortexCommand + 0x62523c)
                #6  0x000064d28660a7ee n/a (/app/lib/CortexCommand/CortexCommand + 0x2937ee)
                #7  0x000064d28660af18 n/a (/app/lib/CortexCommand/CortexCommand + 0x293f18)
                #8  0x000064d2865511c2 n/a (/app/lib/CortexCommand/CortexCommand + 0x1da1c2)
                #9  0x000064d286575f47 n/a (/app/lib/CortexCommand/CortexCommand + 0x1fef47)
                #10 0x000064d2866f94e4 n/a (/app/lib/CortexCommand/CortexCommand + 0x3824e4)
                #11 0x000064d2864c1773 n/a (/app/lib/CortexCommand/CortexCommand + 0x14a773)
                #12 0x000064d28647c0a3 n/a (/app/lib/CortexCommand/CortexCommand + 0x1050a3)
                #13 0x000078b1cf02b3c8 n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x2a3c8)
                #14 0x000078b1cf02b48b n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x2a48b)
                #15 0x000064d2864bfda5 n/a (/app/lib/CortexCommand/CortexCommand + 0x148da5)
                ELF object binary architecture: AMD x86-64

If you can't recreate the issue please let me know, I will try to install debug packages to get a more meaningful stack trace.

### PR DESCRIPTION
**Pull request by Architector4**
In `RunScriptFunctionObject`, script timing is calculated before/after running the script, then written into `PerformanceMan::m_ScriptTimings`  table based on the path to the script. This introduces a use-after-free error and likely crashing if the script in question deallocates the function object, like Combat Shield's "Detach" pie menu option deleting itself: https://github.com/cortex-command-community/Cortex-Command-Community-Project/issues/219

My fix here is to get the table entry *before* running the script, store a pointer to it in a variable, and then access it directly after running the script. This also removes the double lookup into the unordered_map.

In my testing, this fixes the issue entirely. I'm not knowledgeable on this codebase or on C++isms, I don't know what's the policy of the project on raw pointers, so if this doesn't fit, please feel free to disregard this and implement an equivalent kind of a solution in proper language etiquette instead lol

Fixes https://github.com/cortex-command-community/Cortex-Command-Community-Project/issues/219

### CODE REVIEW

File: Source/Managers/LuaMan.cpp [hunk 1]
```diff
@@ -614,8 +614,17 @@ int LuaStateWrapper::RunScriptFunctionObject(const LuabindObjectWrapper* functio
 			functionObjectArgument->GetLuabindObject()->push(m_State);
 		}
 	}
-
 	const std::string& path = functionObject->GetFilePath();
+
+	// Function object may be deleted during the Lua call, making `path` above invalid.
+	// Find and store the script timings entry now and write to it afterward.
+	PerformanceMan::ScriptTiming* timing = NULL;
```
Comment (HeliumAnt) [inline Source/Managers/LuaMan.cpp]:
```suggestion
	PerformanceMan::ScriptTiming* timing = nullptr;
```

File: Source/Managers/LuaMan.cpp [hunk 2]
```diff
@@ -631,10 +640,9 @@ int LuaStateWrapper::RunScriptFunctionObject(const LuabindObjectWrapper* functio
 	}
 	std::chrono::steady_clock::time_point end = std::chrono::steady_clock::now();
 
-	// only track time in non-MT scripts, for now
-	if (&g_LuaMan.GetMasterScriptState() == this) {
-		m_ScriptTimings[path].m_Time += std::chrono::duration_cast<std::chrono::microseconds>(end - begin).count();
-		m_ScriptTimings[path].m_CallCount++;
+	if (timing != NULL) {
```
Comment (HeliumAnt) [inline Source/Managers/LuaMan.cpp]:
```suggestion
	if (timing) {
```

**Review by HeliumAnt — DISMISSED** [review]
Awesome!

**Review by HeliumAnt — APPROVED** [review]

**Review by Causeless — APPROVED** [review]
